//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teacher_Manage_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarWorking
    {
        public int ID { get; set; }
        public string Name_CalendarWorking { get; set; }
        public string Description { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Address { get; set; }
        public int TeacherID { get; set; }
        public int WorkID { get; set; }
        public int TypeCalendarID { get; set; }
        public string WorkState { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Files { get; set; }
    
        public virtual TypeCalendar TypeCalendar { get; set; }
        public virtual Work Work { get; set; }
    }
}
