//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teacher_Manage_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachCalendar
    {
        public int ID { get; set; }
        public string Subject_Name { get; set; }
        public int TeacherID { get; set; }
        public int ClassID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public string Room { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
